import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import '@fontsource/great-vibes/400.css';
import '@fontsource/playfair-display/400.css';
import '@fontsource/playfair-display/400-italic.css';
import '@fontsource/quicksand/400.css';
import '@fontsource/quicksand/600.css';
import './index.css';
createRoot(document.getElementById('root')).render(<App />);
